/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 models/MercedesAMG.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function MercedesAMG(props: any) {
  //@ts-ignore
  const { nodes, materials } = useGLTF("./models/MercedesAMG.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[4.635, 1.882, 1.542]}
        rotation={[0.001, 0, 0]}
        scale={0.021}
      >
        <mesh
          geometry={nodes.uploads_files_313735_MercedesML233.geometry}
          material={materials["マテリアル.009"]}
        />
        <mesh
          geometry={nodes.uploads_files_313735_MercedesML233_1.geometry}
          material={materials["metal.003"]}
        />
        <mesh
          geometry={nodes.uploads_files_313735_MercedesML233_2.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.uploads_files_313735_MercedesML233_3.geometry}
          material={materials.Material}
        />
      </group>
      <group
        position={[-4.427, 1.865, 1.358]}
        rotation={[0.001, 0, 0]}
        scale={0.021}
      >
        <mesh
          geometry={nodes.uploads_files_313735_MercedesML302.geometry}
          material={materials["metal.003"]}
        />
        <mesh
          geometry={nodes.uploads_files_313735_MercedesML302_1.geometry}
          material={materials.Material}
        />
        <mesh
          geometry={nodes.uploads_files_313735_MercedesML302_2.geometry}
          material={materials["マテリアル.009"]}
        />
        <mesh
          geometry={nodes.uploads_files_313735_MercedesML302_3.geometry}
          material={materials["metal.002"]}
        />
        <mesh
          geometry={nodes.uploads_files_313735_MercedesML302_4.geometry}
          material={materials["01___Default"]}
        />
        <mesh
          geometry={nodes.uploads_files_313735_MercedesML302_5.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group
        position={[0.644, 2.171, -1.866]}
        rotation={[0.001, 0, 0]}
        scale={0.021}
      >
        <mesh
          geometry={nodes.uploads_files_313735_MercedesML420.geometry}
          material={materials["Front grill"]}
        />
        <mesh
          geometry={nodes.uploads_files_313735_MercedesML420_1.geometry}
          material={materials.glas}
        />
        <mesh
          geometry={nodes.uploads_files_313735_MercedesML420_2.geometry}
          material={materials["RIM DARK"]}
        />
        <mesh
          geometry={nodes.uploads_files_313735_MercedesML420_3.geometry}
          material={materials["metal.003"]}
        />
        <mesh
          geometry={nodes.uploads_files_313735_MercedesML420_4.geometry}
          material={materials["metal.001"]}
        />
        <mesh
          geometry={nodes.uploads_files_313735_MercedesML420_5.geometry}
          material={materials["metal.002"]}
        />
        <mesh
          geometry={nodes.uploads_files_313735_MercedesML420_6.geometry}
          material={materials["01___Default"]}
        />
        <mesh
          geometry={nodes.uploads_files_313735_MercedesML420_7.geometry}
          material={materials["マテリアル.009"]}
        />
        <mesh
          geometry={nodes.uploads_files_313735_MercedesML420_8.geometry}
          material={materials.Material}
        />
        <mesh
          geometry={nodes.uploads_files_313735_MercedesML420_9.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.uploads_files_313735_MercedesML420_10.geometry}
          material={materials["RIM DARK.001"]}
        />
        <mesh
          geometry={nodes.uploads_files_313735_MercedesML420_11.geometry}
          material={materials["RIM DARK.002"]}
        />
      </group>
      <group
        position={[-7.61, 0.842, 1.947]}
        rotation={[0.001, 0, 0]}
        scale={0.022}
      >
        <mesh
          geometry={nodes.uploads_files_313735_MercedesML427.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.uploads_files_313735_MercedesML427_1.geometry}
          material={materials["metal.002"]}
        />
        <mesh
          geometry={nodes.uploads_files_313735_MercedesML427_2.geometry}
          material={materials["metal.001"]}
        />
        <mesh
          geometry={nodes.uploads_files_313735_MercedesML427_3.geometry}
          material={materials["metal.003"]}
        />
        <mesh
          geometry={nodes.uploads_files_313735_MercedesML427_4.geometry}
          material={materials["wire_000000000.002"]}
        />
      </group>
      <group
        position={[-2.947, 1.069, -1.701]}
        rotation={[-Math.PI / 2, -1.167, Math.PI]}
        scale={0.002}
      >
        <mesh
          geometry={nodes.Lambo_Tire028001.geometry}
          material={materials["wire_000000000.002"]}
        />
        <mesh
          geometry={nodes.Lambo_Tire028001_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Lambo_Tire028001_2.geometry}
          material={materials["metal.002"]}
        />
        <mesh
          geometry={nodes.Lambo_Tire028001_3.geometry}
          material={materials["metal.001"]}
        />
        <mesh
          geometry={nodes.Lambo_Tire028001_4.geometry}
          material={materials["metal.003"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/MercedesAMG.glb");
