/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 models/Mercedes190.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Mercedes190(props: any) {
  //@ts-ignore
  const { nodes, materials } = useGLTF("./models/Mercedes190.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane215.geometry}
        material={materials["Merc Body"]}
        position={[0, 0.601, 0.052]}
      />
      <mesh
        geometry={nodes.Circle003.geometry}
        material={materials["Merc Tyres"]}
        position={[0.62, 0.237, 1.213]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.Circle001.geometry}
        material={materials["Merc Tyres"]}
        position={[-0.62, 0.237, 1.213]}
      />
      <mesh
        geometry={nodes.Circle004.geometry}
        material={materials["Merc Tyres"]}
        position={[0.62, 0.238, -0.844]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.Circle002.geometry}
        material={materials["Merc Tyres"]}
        position={[-0.62, 0.238, -0.844]}
      />
    </group>
  );
}

useGLTF.preload("./models/Mercedes190.glb");
